### ISSUE TITLE
Add BigQuery column description when loading data

### ISSUE THREAD

**Issue by dkapitan** [dkapitan/nimbletl#2]
https://cloud.google.com/bigquery/docs/schemas#column_descriptions

**Comment by TxEddy** [comment]
Was able to add descriptions for the columns in table `TypedDataSet`, these descriptions are loaded from `DataProperties`. To add descriptions for the columns I had to predefine a schema before the data was loaded, if I tried adding descriptions after the data was loaded I would get an error regarding 'Billing....'.

**Comment by dkapitan** [comment]
@TxEddy 
I have just set the billing account for the project dataverbinders-dev.

Please could you try again without specifying a schema? It would be nice if works that way, saves a lot of work.

**Comment by TxEddy** [comment]
@dkapitan So I managed to add descriptions after the data was loaded, but to add these descriptions I had to update the schema. I have not found another way to add descriptions to the columns.

I used the method which predefines a schema to add these descriptions with some small changes to this method. These changes were necessary since BigQuery defines other datatypes then defined in `DataProperties`. So maybe predefining a schema based on `DataProperties` is better and less of a workaround.

In the new commit I commented out the old process.

**Comment by TxEddy** [comment]
Sometimes getting an error saying the table cannot be found, so maybe call the update of the schema after `cbsodatav3_to_bq()` or add a retry to the method?

**Comment by dkapitan** [comment]
@TxEddy 
Probably what is happening is that the first job if creating the table hasn't finished yet. Prefect submits BigQuery jobs asynchronously and returns a Job object which you can poll whether it has completed. Obviously you can only update the table then.
